console.log($);


$(()=>{
  //carousel click to find info
  let indexNum = 1;
  let indexMax = 671;
 //future code will live update when the website increases character count.
//   $.ajax({
//      url: 'https://rickandmortyapi.com/api/character/'
//  }).then(
//     (data) => {
//       console.log(data.info.count);
//       $('.next').on('click', ()=>{
//          if(indexNum<data.info.count)
//       })//wrap all of the code in this Ajax and push indexMax within, set indexMax to be the max id of the value generated by the JSON.
//    }
// )
const infoRemover = () => {
   $('.images').empty();
   $('.species').children().eq(1).empty()
   $('.location').children().eq(1).empty()
   $('.status').children().eq(1).empty()
   $('.type').children().eq(1).empty()
   $('.episodes').children().eq(1).empty()
   $('.gender').children().eq(1).empty()
   $('.name').children().empty()
}

  $.ajax({
    url: "https://rickandmortyapi.com/api/character/" +indexNum
}).then(
      (data) => {
        console.log(data);
         infoRemover();
         $('<img>').attr('src', data.image).appendTo('.images');
         $('.species').children().eq(1).append(data.species)
         $('.location').children().eq(1).append(data.location.name)
         $('.status').children().eq(1).append(data.status)
         $('.type').children().eq(1).append(data.type)
         $('.episodes').children().eq(1).append(data.episode[0])
         $('.gender').children().eq(1).append(data.gender)
         $('.name').children().eq(0).append('NAME: ' + data.name)
         $('.name').children().eq(1).append('ID: ' + data.id + "/671")
         if(data.type === ""){
            $('.type').children().eq(1).text('N/A')
         }
        $('.next').on('click', ()=>{
           if(indexNum<indexMax){
             indexNum++
          }else{
             indexNum=1
          }
           $.ajax({
             url: "https://rickandmortyapi.com/api/character/" +indexNum
          }).then(
             (data) => {
                infoRemover();
                 $('<img>').attr('src', data.image).appendTo('.images');
                 $('.species').children().eq(1).append(data.species)
                 $('.location').children().eq(1).append(data.location.name)
                 $('.status').children().eq(1).append(data.status)
                 $('.type').children().eq(1).append(data.type)
                 $('.episodes').children().eq(1).append(data.episode[0])
                 $('.gender').children().eq(1).append(data.gender)
                 $('.name').children().eq(0).append('NAME: ' + data.name)
                 $('.name').children().eq(1).append('ID: ' + data.id + "/671")
                 if(data.type === ""){
                    $('.type').children().eq(1).text('N/A')
                 }
                 console.log(data);

             })
        })
        $('.back').on('click', ()=>{
          if(indexNum>1){
            indexNum--
         }else{
            indexNum=indexMax
         }
          $.ajax({
            url: "https://rickandmortyapi.com/api/character/" +indexNum
         }).then(
            (data) => {
               infoRemover();
               $('<img>').attr('src', data.image).appendTo('.images');
               $('.species').children().eq(1).append(data.species)
               $('.location').children().eq(1).append(data.location.name)
               $('.status').children().eq(1).append(data.status)
               $('.type').children().eq(1).append(data.type)
               $('.episodes').children().eq(1).append(data.episode[0])
               $('.gender').children().eq(1).append(data.gender)
               $('.name').children().eq(0).append('NAME: ' + data.name)
               $('.name').children().eq(1).append('ID: ' + data.id + "/671")
               if(data.type === ""){
                  $('.type').children().eq(1).text('N/A')
               }
              console.log(data);

            })
       })
        //iterate indexNum to go up and down to display new images for carousel

      })
//search engine goto function
  $('form').on('submit', (event)=>{
    event.preventDefault();
    const userInput = $('input[type="text"]').val();

    $.ajax({
      url: 'https://rickandmortyapi.com/api/character/?name=' + userInput
      }).then(
          (data) => {
             $('.images').empty();
             infoRemover();
              $('<img>').attr('src', data.results[0].image).appendTo('.images');
              $('.species').children().eq(1).append(data.results[0].species)
              $('.location').children().eq(1).append(data.results[0].location.name)
              $('.status').children().eq(1).append(data.results[0].status)
              $('.type').children().eq(1).append(data.results[0].type)
              $('.episodes').children().eq(1).append(data.results[0].episode[0])
              $('.gender').children().eq(1).append(data.results[0].gender)
              $('.name').children().eq(0).append('NAME: ' + data.results[0].name)
              $('.name').children().eq(1).append('ID: ' + data.results[0].id + "/671")
              if(data.type === ""){
                 $('.type').children().eq(1).text('N/A')
              }

             //when searching a character, change indexNum to be new id of character
            console.log(data.results[0]); //must include results[0] to grab 1 search
            indexNum = data.results[0].id
          }
        )



  })
  $('.random').on('click', ()=>{
     indexNum = Math.floor(Math.random()*671)
     $.ajax({
       url: "https://rickandmortyapi.com/api/character/" +indexNum
    }).then(
       (data) => {
          infoRemover();
           $('<img>').attr('src', data.image).appendTo('.images');
           $('.species').children().eq(1).append(data.species)
           $('.location').children().eq(1).append(data.location.name)
           $('.status').children().eq(1).append(data.status)
           $('.type').children().eq(1).append(data.type)
           $('.episodes').children().eq(1).append(data.episode[0])
           $('.gender').children().eq(1).append(data.gender)
           $('.name').children().eq(0).append('NAME: ' + data.name)
           $('.name').children().eq(1).append('ID: ' + data.id + "/671")
           if(data.type === ""){
              $('.type').children().eq(1).text('N/A')
           }
         console.log(data);

       })

 })












})
