console.log($);


$(()=>{
  //carousel click to find info
  let indexNum = 1;
  let indexMax = 671;

 //future code will live update when the website increases character count.
 $('.navUp').children().on('click', ()=> {
    $('html,body').scrollTop(150);
    console.log('I see you clicked');
})
$('.navDown').children().on('click', ()=> {
   $('html,body').scrollTop(100000);
   console.log('I see you clicked');
})
  $.ajax({
     url: 'https://rickandmortyapi.com/api/character/'
 }).then(
    (data) => {
      // console.log(data.info.count);
      // $('.next').on('click', ()=>{
      //    if(indexNum<data.info.count)
      // })//wrap all of the code in this Ajax and push indexMax within, set indexMax to be the max id of the value generated by the JSON.
const infoRemover = () => {
   $('.images').empty();
   $('.species').children().eq(1).empty()
   $('.location').children().eq(1).empty()
   $('.status').children().eq(1).empty()
   $('.type').children().eq(1).empty()
   $('.episodes').children().eq(1).empty()
   $('.gender').children().eq(1).empty()
   $('.name').children().empty()
}
//creates baseline site info opening with Rick Sanchez to load with site
  $.ajax({
    url: "https://rickandmortyapi.com/api/character/" +indexNum
}).then(
      (data) => {
        console.log(data);
         infoRemover();
         $('<img>').attr('src', data.image).appendTo('.images');
         $('.species').children().eq(1).append(data.species)
         $('.location').children().eq(1).append(data.location.name)
         $('.status').children().eq(1).append(data.status)
         $('.type').children().eq(1).append(data.type)
         //$('.episodes').children().eq(1).append(data.episode[0])
         $('.gender').children().eq(1).append(data.gender)
         $('.name').children().eq(0).append('NAME: ' + data.name)
         $('.name').children().eq(1).append('ID: ' + data.id + "/671")
         if(data.type === ""){
            $('.type').children().eq(1).text('N/A')
         const episode = data.episode[0]
         console.log(episode);
         }
         //ajax calls for the episode information!
         $.ajax({
            url: data.episode[0]
         }).then(
               (data) => {
            console.log(data);
            $('.episodes').children().eq(1).append(data.episode).append(` "${data.name}"`)
         })
   })
         //clicking next on the screen will load the next page over!
        $('.next').on('click', ()=>{
           if(indexNum<indexMax){
             indexNum++
          }else{
             indexNum=1
          }
           $.ajax({
             url: "https://rickandmortyapi.com/api/character/" +indexNum
          }).then(
             (data) => {
                infoRemover();
                 $('<img>').attr('src', data.image).appendTo('.images');
                 $('.species').children().eq(1).append(data.species)
                 $('.location').children().eq(1).append(data.location.name)
                 $('.status').children().eq(1).append(data.status)
                 $('.type').children().eq(1).append(data.type)
                // $('.episodes').children().eq(1).append(data.episode[0])
                 $('.gender').children().eq(1).append(data.gender)
                 $('.name').children().eq(0).append('NAME: ' + data.name)
                 $('.name').children().eq(1).append('ID: ' + data.id + "/671")
                 if(data.type === ""){
                    $('.type').children().eq(1).text('N/A')
                 }
                 console.log(data);
                 $.ajax({
                    url: data.episode[0]
                 }).then(
                       (data) => {
                    console.log(data);
                    $('.episodes').children().eq(1).append(data.episode).append(` "${data.name}"`)
                 })
             })
        })
        //clicking back will load the previous page!
        $('.back').on('click', ()=>{
          if(indexNum>1){
            indexNum--
         }else{
            indexNum=indexMax
         }
          $.ajax({
            url: "https://rickandmortyapi.com/api/character/" +indexNum
         }).then(
            (data) => {
               infoRemover();
               $('<img>').attr('src', data.image).appendTo('.images');
               $('.species').children().eq(1).append(data.species)
               $('.location').children().eq(1).append(data.location.name)
               $('.status').children().eq(1).append(data.status)
               $('.type').children().eq(1).append(data.type)
               //$('.episodes').children().eq(1).append(data.episode[0])
               $('.gender').children().eq(1).append(data.gender)
               $('.name').children().eq(0).append('NAME: ' + data.name)
               $('.name').children().eq(1).append('ID: ' + data.id + "/671")
               if(data.type === ""){
                  $('.type').children().eq(1).text('N/A')
               }
              console.log(data);
              $.ajax({
                 url: data.episode[0]
              }).then(
                    (data) => {
                 console.log(data);
                 $('.episodes').children().eq(1).append(data.episode).append(` "${data.name}"`)
              })
            })
       })
        //iterate indexNum to go up and down to display new images for carousel


//search engine goto function
  $('form').on('submit', (event)=>{
    event.preventDefault();
    const userInput = $('input[type="text"]').val();

    $.ajax({
      url: 'https://rickandmortyapi.com/api/character/?name=' + userInput
      }).then(
          (data) => {
             $('.images').empty();
             infoRemover();
              $('<img>').attr('src', data.results[0].image).appendTo('.images');
              $('.species').children().eq(1).append(data.results[0].species)
              $('.location').children().eq(1).append(data.results[0].location.name)
              $('.status').children().eq(1).append(data.results[0].status)
              $('.type').children().eq(1).append(data.results[0].type)
             // $('.episodes').children().eq(1).append(data.results[0].episode[0])
              $('.gender').children().eq(1).append(data.results[0].gender)
              $('.name').children().eq(0).append('NAME: ' + data.results[0].name)
              $('.name').children().eq(1).append('ID: ' + data.results[0].id + "/671")
              if(data.results[0].type === ""){
                 $('.type').children().eq(1).text('N/A')
              }
              $.ajax({
                 url: data.results[0].episode[0]
              }).then(
                    (data) => {
                 console.log(data);
                 $('.episodes').children().eq(1).append(data.episode).append(` "${data.name}"`)
              })
             //when searching a character, change indexNum to be new id of character
            console.log(data.results[0]); //must include results[0] to grab 1 search
            indexNum = data.results[0].id
          }
        )
      $('input[type="text"]').val('')


  })
  //random button to go to a random ID of the site.
  $('.random').on('click', ()=>{
     indexNum = Math.floor(Math.random()*671)
     $.ajax({
       url: "https://rickandmortyapi.com/api/character/" +indexNum
    }).then(
       (data) => {
          infoRemover();
           $('<img>').attr('src', data.image).appendTo('.images');
           $('.species').children().eq(1).append(data.species)
           $('.location').children().eq(1).append(data.location.name)
           $('.status').children().eq(1).append(data.status)
           $('.type').children().eq(1).append(data.type)
          // $('.episodes').children().eq(1).append(data.episode[0])
           $('.gender').children().eq(1).append(data.gender)
           $('.name').children().eq(0).append('NAME: ' + data.name)
           $('.name').children().eq(1).append('ID: ' + data.id + "/671")
           if(data.type === ""){
              $('.type').children().eq(1).text('N/A')
           }
         console.log(data);
         $.ajax({
            url: data.episode[0]
         }).then(
               (data) => {
            console.log(data);
            $('.episodes').children().eq(1).append(data.episode).append(` "${data.name}"`)
         })
       })

 })

// $('document').on('swipeleft', ()=> {
//    console.log('that was a swipe left');
//    if(indexNum>1){
//      indexNum++
//   }else{
//      indexNum=indexMax
//   }
//    $.ajax({
//      url: "https://rickandmortyapi.com/api/character/" +indexNum
//   }).then(
//      (data) => {
//         infoRemover();
//         $('<img>').attr('src', data.image).appendTo('.images');
//         $('.species').children().eq(1).append(data.species)
//         $('.location').children().eq(1).append(data.location.name)
//         $('.status').children().eq(1).append(data.status)
//         $('.type').children().eq(1).append(data.type)
//         //$('.episodes').children().eq(1).append(data.episode[0])
//         $('.gender').children().eq(1).append(data.gender)
//         $('.name').children().eq(0).append('NAME: ' + data.name)
//         $('.name').children().eq(1).append('ID: ' + data.id + "/671")
//         if(data.type === ""){
//            $('.type').children().eq(1).text('N/A')
//         }
//        console.log(data);
//        $.ajax({
//           url: data.episode[0]
//        }).then(
//              (data) => {
//           console.log(data);
//           $('.episodes').children().eq(1).append(data.episode).append(` "${data.name}"`)
//        })
//      })
// }) //needs JQuery mobile functionality?







}
)



})
